components:
  schemas:
    Products:
      type: object
      properties:
        _id:
          type: ObjectId
          description: Id autogenerado por Mongo.
        title:
          type: String
          description: Nombre del producto
        description:
          type: String
          description: Descripción del producto
        code:
          type: String
          description: Codigo unico del producto
        price:
          type: Number
          description: Precio del producto
        status:
          type: Boolean
          description: Status del producto
        stock:
          type: Number
          description: Stock del producto
        category:
          type: String
          description: Categoria del producto
        thumbnail:
          type: String
          description: Imagenes del producto
        owner:
          type: String
          description: Creador del producto
      example:
        products:
          {
            status: succes,
            payload:
              [
                {
                  _id: "65aeae876b453f347edf2125",
                  title: Apple Watch,
                  description: Smart watch,
                  code: Apple4,
                  price: 300,
                  status: true,
                  stock: 19,
                  category: Electronica,
                  thumbnail: data:image/jpeg;base64,
                  owner: admin,
                },
              ],
          }
